-------------------------------------------------------------------------------
Test set: com.farao_communityfarao.cse_valid.api.exception.CseValidInvalidDataExceptionTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in com.farao_communityfarao.cse_valid.api.exception.CseValidInvalidDataExceptionTest
